/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EstudiantePagosRouteImport } from './routes/estudiante/pagos'
import { Route as EstudianteNotasRouteImport } from './routes/estudiante/notas'
import { Route as EstudianteMensajeriaRouteImport } from './routes/estudiante/mensajeria'
import { Route as EstudianteMatriculaRouteImport } from './routes/estudiante/matricula'
import { Route as EstudianteDashboardRouteImport } from './routes/estudiante/dashboard'
import { Route as EstudianteBibliotecaRouteImport } from './routes/estudiante/biblioteca'
import { Route as DocenteNotasRouteImport } from './routes/docente/notas'
import { Route as DocenteMensajeriaRouteImport } from './routes/docente/mensajeria'
import { Route as DocenteMaterialesRouteImport } from './routes/docente/materiales'
import { Route as DocenteDashboardRouteImport } from './routes/docente/dashboard'
import { Route as DocenteCursosRouteImport } from './routes/docente/cursos'
import { Route as DocenteAsistenciaRouteImport } from './routes/docente/asistencia'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AdminReportesRouteImport } from './routes/admin/reportes'
import { Route as AdminMensajeriaRouteImport } from './routes/admin/mensajeria'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCursosRouteImport } from './routes/admin/cursos'
import { Route as AdminConfiguracionRouteImport } from './routes/admin/configuracion'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudiantePagosRoute = EstudiantePagosRouteImport.update({
  id: '/estudiante/pagos',
  path: '/estudiante/pagos',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudianteNotasRoute = EstudianteNotasRouteImport.update({
  id: '/estudiante/notas',
  path: '/estudiante/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudianteMensajeriaRoute = EstudianteMensajeriaRouteImport.update({
  id: '/estudiante/mensajeria',
  path: '/estudiante/mensajeria',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudianteMatriculaRoute = EstudianteMatriculaRouteImport.update({
  id: '/estudiante/matricula',
  path: '/estudiante/matricula',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudianteDashboardRoute = EstudianteDashboardRouteImport.update({
  id: '/estudiante/dashboard',
  path: '/estudiante/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudianteBibliotecaRoute = EstudianteBibliotecaRouteImport.update({
  id: '/estudiante/biblioteca',
  path: '/estudiante/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const DocenteNotasRoute = DocenteNotasRouteImport.update({
  id: '/docente/notas',
  path: '/docente/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const DocenteMensajeriaRoute = DocenteMensajeriaRouteImport.update({
  id: '/docente/mensajeria',
  path: '/docente/mensajeria',
  getParentRoute: () => rootRouteImport,
} as any)
const DocenteMaterialesRoute = DocenteMaterialesRouteImport.update({
  id: '/docente/materiales',
  path: '/docente/materiales',
  getParentRoute: () => rootRouteImport,
} as any)
const DocenteDashboardRoute = DocenteDashboardRouteImport.update({
  id: '/docente/dashboard',
  path: '/docente/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocenteCursosRoute = DocenteCursosRouteImport.update({
  id: '/docente/cursos',
  path: '/docente/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const DocenteAsistenciaRoute = DocenteAsistenciaRouteImport.update({
  id: '/docente/asistencia',
  path: '/docente/asistencia',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportesRoute = AdminReportesRouteImport.update({
  id: '/admin/reportes',
  path: '/admin/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMensajeriaRoute = AdminMensajeriaRouteImport.update({
  id: '/admin/mensajeria',
  path: '/admin/mensajeria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCursosRoute = AdminCursosRouteImport.update({
  id: '/admin/cursos',
  path: '/admin/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/admin/configuracion',
  path: '/admin/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/mensajeria': typeof AdminMensajeriaRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/docente/asistencia': typeof DocenteAsistenciaRoute
  '/docente/cursos': typeof DocenteCursosRoute
  '/docente/dashboard': typeof DocenteDashboardRoute
  '/docente/materiales': typeof DocenteMaterialesRoute
  '/docente/mensajeria': typeof DocenteMensajeriaRoute
  '/docente/notas': typeof DocenteNotasRoute
  '/estudiante/biblioteca': typeof EstudianteBibliotecaRoute
  '/estudiante/dashboard': typeof EstudianteDashboardRoute
  '/estudiante/matricula': typeof EstudianteMatriculaRoute
  '/estudiante/mensajeria': typeof EstudianteMensajeriaRoute
  '/estudiante/notas': typeof EstudianteNotasRoute
  '/estudiante/pagos': typeof EstudiantePagosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/mensajeria': typeof AdminMensajeriaRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/docente/asistencia': typeof DocenteAsistenciaRoute
  '/docente/cursos': typeof DocenteCursosRoute
  '/docente/dashboard': typeof DocenteDashboardRoute
  '/docente/materiales': typeof DocenteMaterialesRoute
  '/docente/mensajeria': typeof DocenteMensajeriaRoute
  '/docente/notas': typeof DocenteNotasRoute
  '/estudiante/biblioteca': typeof EstudianteBibliotecaRoute
  '/estudiante/dashboard': typeof EstudianteDashboardRoute
  '/estudiante/matricula': typeof EstudianteMatriculaRoute
  '/estudiante/mensajeria': typeof EstudianteMensajeriaRoute
  '/estudiante/notas': typeof EstudianteNotasRoute
  '/estudiante/pagos': typeof EstudiantePagosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/mensajeria': typeof AdminMensajeriaRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/docente/asistencia': typeof DocenteAsistenciaRoute
  '/docente/cursos': typeof DocenteCursosRoute
  '/docente/dashboard': typeof DocenteDashboardRoute
  '/docente/materiales': typeof DocenteMaterialesRoute
  '/docente/mensajeria': typeof DocenteMensajeriaRoute
  '/docente/notas': typeof DocenteNotasRoute
  '/estudiante/biblioteca': typeof EstudianteBibliotecaRoute
  '/estudiante/dashboard': typeof EstudianteDashboardRoute
  '/estudiante/matricula': typeof EstudianteMatriculaRoute
  '/estudiante/mensajeria': typeof EstudianteMensajeriaRoute
  '/estudiante/notas': typeof EstudianteNotasRoute
  '/estudiante/pagos': typeof EstudiantePagosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/configuracion'
    | '/admin/cursos'
    | '/admin/dashboard'
    | '/admin/mensajeria'
    | '/admin/reportes'
    | '/admin/usuarios'
    | '/docente/asistencia'
    | '/docente/cursos'
    | '/docente/dashboard'
    | '/docente/materiales'
    | '/docente/mensajeria'
    | '/docente/notas'
    | '/estudiante/biblioteca'
    | '/estudiante/dashboard'
    | '/estudiante/matricula'
    | '/estudiante/mensajeria'
    | '/estudiante/notas'
    | '/estudiante/pagos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/configuracion'
    | '/admin/cursos'
    | '/admin/dashboard'
    | '/admin/mensajeria'
    | '/admin/reportes'
    | '/admin/usuarios'
    | '/docente/asistencia'
    | '/docente/cursos'
    | '/docente/dashboard'
    | '/docente/materiales'
    | '/docente/mensajeria'
    | '/docente/notas'
    | '/estudiante/biblioteca'
    | '/estudiante/dashboard'
    | '/estudiante/matricula'
    | '/estudiante/mensajeria'
    | '/estudiante/notas'
    | '/estudiante/pagos'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/configuracion'
    | '/admin/cursos'
    | '/admin/dashboard'
    | '/admin/mensajeria'
    | '/admin/reportes'
    | '/admin/usuarios'
    | '/docente/asistencia'
    | '/docente/cursos'
    | '/docente/dashboard'
    | '/docente/materiales'
    | '/docente/mensajeria'
    | '/docente/notas'
    | '/estudiante/biblioteca'
    | '/estudiante/dashboard'
    | '/estudiante/matricula'
    | '/estudiante/mensajeria'
    | '/estudiante/notas'
    | '/estudiante/pagos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminCursosRoute: typeof AdminCursosRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMensajeriaRoute: typeof AdminMensajeriaRoute
  AdminReportesRoute: typeof AdminReportesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  DocenteAsistenciaRoute: typeof DocenteAsistenciaRoute
  DocenteCursosRoute: typeof DocenteCursosRoute
  DocenteDashboardRoute: typeof DocenteDashboardRoute
  DocenteMaterialesRoute: typeof DocenteMaterialesRoute
  DocenteMensajeriaRoute: typeof DocenteMensajeriaRoute
  DocenteNotasRoute: typeof DocenteNotasRoute
  EstudianteBibliotecaRoute: typeof EstudianteBibliotecaRoute
  EstudianteDashboardRoute: typeof EstudianteDashboardRoute
  EstudianteMatriculaRoute: typeof EstudianteMatriculaRoute
  EstudianteMensajeriaRoute: typeof EstudianteMensajeriaRoute
  EstudianteNotasRoute: typeof EstudianteNotasRoute
  EstudiantePagosRoute: typeof EstudiantePagosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiante/pagos': {
      id: '/estudiante/pagos'
      path: '/estudiante/pagos'
      fullPath: '/estudiante/pagos'
      preLoaderRoute: typeof EstudiantePagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiante/notas': {
      id: '/estudiante/notas'
      path: '/estudiante/notas'
      fullPath: '/estudiante/notas'
      preLoaderRoute: typeof EstudianteNotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiante/mensajeria': {
      id: '/estudiante/mensajeria'
      path: '/estudiante/mensajeria'
      fullPath: '/estudiante/mensajeria'
      preLoaderRoute: typeof EstudianteMensajeriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiante/matricula': {
      id: '/estudiante/matricula'
      path: '/estudiante/matricula'
      fullPath: '/estudiante/matricula'
      preLoaderRoute: typeof EstudianteMatriculaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiante/dashboard': {
      id: '/estudiante/dashboard'
      path: '/estudiante/dashboard'
      fullPath: '/estudiante/dashboard'
      preLoaderRoute: typeof EstudianteDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiante/biblioteca': {
      id: '/estudiante/biblioteca'
      path: '/estudiante/biblioteca'
      fullPath: '/estudiante/biblioteca'
      preLoaderRoute: typeof EstudianteBibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docente/notas': {
      id: '/docente/notas'
      path: '/docente/notas'
      fullPath: '/docente/notas'
      preLoaderRoute: typeof DocenteNotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docente/mensajeria': {
      id: '/docente/mensajeria'
      path: '/docente/mensajeria'
      fullPath: '/docente/mensajeria'
      preLoaderRoute: typeof DocenteMensajeriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docente/materiales': {
      id: '/docente/materiales'
      path: '/docente/materiales'
      fullPath: '/docente/materiales'
      preLoaderRoute: typeof DocenteMaterialesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docente/dashboard': {
      id: '/docente/dashboard'
      path: '/docente/dashboard'
      fullPath: '/docente/dashboard'
      preLoaderRoute: typeof DocenteDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docente/cursos': {
      id: '/docente/cursos'
      path: '/docente/cursos'
      fullPath: '/docente/cursos'
      preLoaderRoute: typeof DocenteCursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docente/asistencia': {
      id: '/docente/asistencia'
      path: '/docente/asistencia'
      fullPath: '/docente/asistencia'
      preLoaderRoute: typeof DocenteAsistenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reportes': {
      id: '/admin/reportes'
      path: '/admin/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AdminReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mensajeria': {
      id: '/admin/mensajeria'
      path: '/admin/mensajeria'
      fullPath: '/admin/mensajeria'
      preLoaderRoute: typeof AdminMensajeriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cursos': {
      id: '/admin/cursos'
      path: '/admin/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AdminCursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/admin/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminCursosRoute: AdminCursosRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMensajeriaRoute: AdminMensajeriaRoute,
  AdminReportesRoute: AdminReportesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  DocenteAsistenciaRoute: DocenteAsistenciaRoute,
  DocenteCursosRoute: DocenteCursosRoute,
  DocenteDashboardRoute: DocenteDashboardRoute,
  DocenteMaterialesRoute: DocenteMaterialesRoute,
  DocenteMensajeriaRoute: DocenteMensajeriaRoute,
  DocenteNotasRoute: DocenteNotasRoute,
  EstudianteBibliotecaRoute: EstudianteBibliotecaRoute,
  EstudianteDashboardRoute: EstudianteDashboardRoute,
  EstudianteMatriculaRoute: EstudianteMatriculaRoute,
  EstudianteMensajeriaRoute: EstudianteMensajeriaRoute,
  EstudianteNotasRoute: EstudianteNotasRoute,
  EstudiantePagosRoute: EstudiantePagosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
